version: "3"

services:
  api:
    container_name: svc_bankfrick
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./:/webapps
    command: tail -f /dev/null
